import pytest
import json
from unittest.mock import patch, MagicMock

from app.detectors.brand_intel import (
    get_brand_permutations,
    check_domain_against_brands,
    BrandMatch
)

@pytest.fixture
def mock_redis():
    with patch("app.detectors.brand_intel._get_redis_client") as mock_get:
        mock_client = MagicMock()
        mock_get.return_value = mock_client
        mock_client.get.return_value = None
        yield mock_client

def test_known_lookalike_domain(mock_redis):
    # amazon.com -> amazom.com is generated by dnstwist
    match = check_domain_against_brands("amazom.com")
    assert match is not None
    assert isinstance(match, BrandMatch)
    assert match.matched_brand == "amazon"
    assert match.domain == "amazom.com"
    mock_redis.setex.assert_called()

def test_unrelated_domain(mock_redis):
    match = check_domain_against_brands("totally-unrelated-random-domain.xyz")
    assert match is None

def test_redis_caching_logic(mock_redis):
    # First call sets cache
    get_brand_permutations("testbrand.com")
    mock_redis.get.assert_called_with("dnstwist:testbrand.com")
    mock_redis.setex.assert_called()
    
    mock_redis.reset_mock()
    
    # Second call gets from cache
    mock_redis.get.return_value = json.dumps([{"fuzzer": "test", "domain": "testbrand.com"}])
    perms = get_brand_permutations("testbrand.com")
    
    mock_redis.get.assert_called_with("dnstwist:testbrand.com")
    mock_redis.setex.assert_not_called()
    assert len(perms) == 1
    assert perms[0]["domain"] == "testbrand.com"
